#!/bin/bash -e
#
# MELODIC Boot Splash Script
# Copyright (C) 2017-2018 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

SCRIPT_BASE=.
MAKE_CROPPED=$SCRIPT_BASE/image-resize-with-cropping


MAKEFILE="Makefile.bootsplash"
SPLASH_DIMENSIONS="1024x768"
VARIANT="plain"
JPEG_QUALITY=92.5
INPUTS=`find Output/Desktop-with-Logo/ -maxdepth 1 -name "[A-Z]*-${VARIANT}-${SPLASH_DIMENSIONS}.png" -or -name "[A-Z]*-${VARIANT}-${SPLASH_DIMENSIONS}.jpeg"`


# ====== Handle arguments ===================================================
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 caption_file"
   exit 1
fi
CAPTION_FILE="$1"
if [ ! -e "$CAPTION_FILE" ] ; then
   echo >&2 "ERROR: Cannot find caption file $CAPTION_FILE!"
   exit 1
fi


# ====== Initialize Makefile ================================================
rm -f $MAKEFILE
(
   echo ""
   echo -e "all:\tdirectories all-images"
   echo ""
   echo "directories:"
   echo -e "\t@mkdir -p Output/Splash"
   echo ""
) >$MAKEFILE


# ====== Create caption =====================================================
splashWidth=`echo "$SPLASH_DIMENSIONS" | sed -e "s/^\([0-9]*\)x\(.*\)$/\1/g"`
(
   echo -e "Output/Text/Caption-$SPLASH_DIMENSIONS.png:\t${CAPTION_FILE}"
   echo -e "\t@echo \"Making Output/Text/Caption-$SPLASH_DIMENSIONS.png ...\""
   echo -e "\t@convert -background Gold -fill \"#02266b\" -font Helvetica-Bold -pointsize 24 -gravity Center -size ${splashWidth}x42 \\"
   echo -e "\t   caption:\"\`cat ${CAPTION_FILE} | head -n1\`\" \\"
   echo -e "\t   Output/Text/Caption-$SPLASH_DIMENSIONS.png"
   echo ""
) >>$MAKEFILE


# ====== Create bootsplashes ================================================
for inputFile in $INPUTS ; do
   name=`basename "$inputFile" | sed -e "s/-${VARIANT}-${SPLASH_DIMENSIONS}\.[a-zA-Z]*$//g"`
   
   (
      echo -e "Output/Splash/$name-$SPLASH_DIMENSIONS.jpeg:\tOutput/Text/Caption-$SPLASH_DIMENSIONS.png"
      echo -e "\t@echo \"Making Output/Splash/$name-$SPLASH_DIMENSIONS.jpeg ...\""
      echo -e "\t@convert -size ${SPLASH_DIMENSIONS} xc:skyblue \\"
      echo -e "\t   \\( $inputFile \\) -gravity center -composite \\"
      echo -e "\t   \\( Output/Text/Caption-$SPLASH_DIMENSIONS.png \\) -gravity South -composite \\"
      echo -e "\t   -quality ${JPEG_QUALITY} \\"
      echo -e "\t   Output/Splash/$name-$SPLASH_DIMENSIONS.jpeg"
      echo -e "\t@exiftool -q -overwrite_original -Copyright=\"Copyright `date '+%Y'` by Thomas Dreibholz\" \\"
      echo -e "\t   Output/Splash/$name-$SPLASH_DIMENSIONS.jpeg"
      echo ""
   ) >>$MAKEFILE

   allImages="$allImages Output/Splash/$name-$SPLASH_DIMENSIONS.jpeg"
   
done

(
   echo -e "\nall-images:\t$allImages"
   echo ""
) >>$MAKEFILE


# ====== Make everything ====================================================
cores=`getconf _NPROCESSORS_ONLN`
make -j${cores} -f $MAKEFILE
