#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Image Best-Fit (resize with cropping, keeping aspect ratio)
# Copyright (C) 2012-2017 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

import sys
import math
import wand
import wand.image


if len(sys.argv) != 4:
   print(('Usage: ' + sys.argv[0] + ' [Input] [Output] [Aspect|A4]'))
   exit(1)

inputFileName  = sys.argv[1]
outputFileName = sys.argv[2]
if ((sys.argv[3] == 'A4') or (sys.argv[3] == 'a4')):
   outputAspect = math.sqrt(2)
else:
   outputAspect = float(sys.argv[3])

try:
   image = wand.image.Image(filename=inputFileName)
except Exception:
   sys.stderr.write('ERROR: Unable to open file ' + inputFileName + '!\n')
   sys.exit(1)

inputWidth  = 0.0 + image.width    # Use float!
inputHeight = 0.0 + image.height   # Use float!
inputAspect = inputWidth / inputHeight      # => result is also float!
if inputAspect < 1.0:
   outputAspect = 1 / outputAspect   # Portrait


#print('Input:  ' + inputFileName + ' ' + str(inputWidth) + '*' + str(inputHeight) + ' (' + str(inputAspect) + ':1)')
if inputAspect < outputAspect:
   newWidth  = int(inputWidth)
   newHeight = int(round(newWidth / outputAspect))
else:
   newHeight = int(inputHeight)
   newWidth  = int(round(inputHeight * outputAspect))

cropWidth  = int(inputWidth - newWidth)
cropHeight = int(inputHeight - newHeight)
#print(' -> crop: w=' + str(cropWidth) + ' h=' + str(cropHeight))

#print('Output: ' + outputFileName + ' ' + str(newWidth) + '*' + str(newHeight) + ' (' + str(outputAspect) + ':1)')
image.crop(int(cropWidth / 2), int(cropHeight / 2),
           width=newWidth, height=newHeight)
image.save(filename=outputFileName)
