#!/bin/bash -e
#
# Convert image(s) to PDF in DIN A4 format
# Copyright (C) 2017 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

MAKE_CROPPED=./image-resize-with-cropping

if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 output_file input_file [input_file [...]]"
   exit 1
fi


# ====== Convert and crop input files =======================================
outputFile="$1"
tempDirectory=`mktemp -d -t tmp.XXXXXXXXXX`
inputPages=""

page=1
while [ $# -gt 1 ] ; do
   shift
   inputFile="$1"
   tempFile="$tempDirectory/${page}.png"

   ${MAKE_CROPPED} "$inputFile" $tempFile A4

   inputPages="$inputPages $tempFile"
   let page=$page+1
done


# ====== Write output file ==================================================
# DIN A4: 210 mm × 297 mm
WIDTH=2970
HEIGHT=2100

convert \
 -units PixelsPerCentimeter -density 100x100 -page ${WIDTH}x${HEIGHT} -resize ${WIDTH}x${HEIGHT} \
 -gravity center \
 -compress lossless \
 $inputPages \
 "$outputFile"
identify "$outputFile"

rm -rf "$tempDirectory"
