#!/bin/bash -e
#
# MELODIC Logo Script
# Copyright (C) 2017 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -lt 3 ] ; then
   echo >&2 "Usage: $0 output_file width height"
   exit 1
fi
OUTPUT="$1"
WIDTH="$2"
HEIGHT="$3"

prefix="MELODIC"

# ------ Proportions --------------------------------------------------------
titleWidth=0.75      # of Width
subtitleWidth=0.80   # of Width
nameHeight=0.035     # of Height
titleBorder=0.50     # of Name Height
nameBorder=0.35      # of Name Height
indent=0.055         # of Height


# ------ Create logo --------------------------------------------------------
titleWidthValue=`echo "${WIDTH}*${titleWidth}" | bc -l`
subtitleWidthValue=`echo "${WIDTH}*${subtitleWidth}" | bc -l`
nameHeightValue=`echo "${HEIGHT}*${nameHeight}" | bc -l`
titleBorderValue=`echo "${nameHeightValue}*${titleBorder}" | bc -l`
nameBorderValue=`echo "${nameHeightValue}*${nameBorder}" | bc -l`
indentValue=`echo "${HEIGHT}*${indent}" | bc -l`

convert -size ${WIDTH}x${HEIGHT} xc:none \
   \( -background none \
      \( $prefix-Title.png       -trim +repage -resize ${titleWidthValue}x \) -gravity center -append \
      \( $prefix-Subtitle.png    -trim +repage -resize ${subtitleWidthValue}x -bordercolor none -border 0x${titleBorderValue} \) -gravity south  -append \) -gravity center -composite \
   \( -background none \
      \( $prefix-Name.png        -trim +repage -resize x${nameHeightValue} \) -gravity center -append \
      \( $prefix-Affiliation.png -trim +repage -resize x${nameHeightValue} -bordercolor none -border 0x${nameBorderValue} \) -gravity south  -append \
      \( $prefix-URL.png         -trim +repage -resize x${nameHeightValue} \) -gravity south  -append \) \
         -gravity southeast -geometry +${indentValue}+${indentValue} -composite \
"$OUTPUT"

#    \( $prefix-hostname.png       -trim +repage -resize x${hostHeight} \) \
#       -gravity north -geometry +0+${indent} -composite \
