#!/bin/bash

DIRECTORY="/vservers"
VARIANTS="trusty xenial zesty artful" # bionic"

for variant in $VARIANTS ; do
   mkdir -p "$variant"

   (
      LOCATION="http://no.archive.ubuntu.com/ubuntu/dists/$variant/main/installer-amd64/"
      if [ "$variant" == "trusty" ] ; then
         # Trusty: No updates during installation. Kernels needs to be upgraded later manually.
         sed -e "s/xenial/$variant/g" \
             -e "s/^d-i pkgsel\/upgrade.*\$/d-i pkgsel\/upgrade select none/g" \
             -e "s/in-target true # <SET_POSTINSTALL_COMMANDS_HERE>.*\$/in-target apt-get install -y linux-generic-lts-xenial/g" \
            <preseed.cfg >$variant/preseed.cfg
      elif [ "$variant" == "xenial" ] ; then
         # Xenial: Use HWE kernel
         sed -e "s/xenial/$variant/g" \
             -e "s/^# d-i base-installer\/kernel\/override-image.*$/d-i base-installer\/kernel\/override-image string linux-generic-hwe-16.04/g" \
            <preseed.cfg >$variant/preseed.cfg
      else
         sed -e "s/xenial/$variant/g" <preseed.cfg >$variant/preseed.cfg
      fi

      NAME="Ubuntu-`echo "$variant" | sed  -e's/^\(.\)/\U\1/'`"
      IMAGE="$DIRECTORY/$NAME.qcow2"

      virsh -c qemu:///system destroy  "$NAME" >/dev/null 2>&1
      virsh -c qemu:///system undefine "$NAME" >/dev/null 2>&1
      rm -f "$IMAGE"

      qemu-img create -f qcow2 -o size=16G $IMAGE && \
      virt-install \
         --name "$NAME" \
         --ram 1024 \
         --disk "path=$IMAGE,format=qcow2,cache=unsafe" \
         --network bridge=virbr0,model=virtio \
         --vcpus 1 \
         --video qxl --channel spicevmc \
         --os-type linux \
         --os-variant ubuntu16.04 \
         --location "$LOCATION" \
         --initrd-inject=$variant/preseed.cfg \
         --extra-args 'net.ifnames=0 biosdevname=0 vga=792 priority=critical file=preseed.cfg preseed/file=preseed.cfg' \
         --noreboot

      # For serial console instead of graphics output:
      # --graphics none
      # --console pty,target_type=serial
      # --extra-args 'console=ttyS0 ...

      # reset
      # clear

      virt-sysprep -a $IMAGE
   ) &
done
