background/Desktop-with-Logo/*.jpeg      /usr/share/melodic-desktop/Desktop-with-Logo
background/Desktop-with-Logo/*.png       /usr/share/melodic-desktop/Desktop-with-Logo
# background/Desktop-without-Logo/*.jpeg   /usr/share/melodic-desktop/Desktop-without-Logo
# background/Desktop-without-Logo/*.png    /usr/share/melodic-desktop/Desktop-without-Logo
# background/Original/*.jpeg               /usr/share/melodic-desktop/Original
# background/Original/*.png                /usr/share/melodic-desktop/Original
