#!/bin/bash -e
#
# MELODIC Logo Script
# Copyright (C) 2017-2018 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -lt 4 ] ; then
   echo >&2 "Usage: $0 output_file width height input_directory"
   exit 1
fi
OUTPUT="$1"
WIDTH="$2"
HEIGHT="$3"
DIRECTORY="$4"

# ------ Proportions --------------------------------------------------------
titleWidth=0.75      # of Width
subtitleWidth=0.80   # of Width
nameHeight=0.035     # of Height
titleBorder=0.50     # of Name Height
nameBorder=0.35      # of Name Height
indent=0.055         # of Height


# ------ Create logo --------------------------------------------------------
titleWidthValue=`awk "BEGIN { print ${WIDTH}*${titleWidth} }"`
subtitleWidthValue=`awk "BEGIN { print ${WIDTH}*${subtitleWidth} }"`
nameHeightValue=`awk "BEGIN { print ${HEIGHT}*${nameHeight} }"`
titleBorderValue=`awk "BEGIN { print ${nameHeightValue}*${titleBorder} }"`
nameBorderValue=`awk "BEGIN { print ${nameHeightValue}*${nameBorder} }"`
indentValue=`awk "BEGIN { print ${HEIGHT}*${indent} }"`

# convert -size ${WIDTH}x${HEIGHT} xc:none \
#     -background none \
#        $DIRECTORY/Title.png       -trim +repage -resize ${titleWidthValue}x  -gravity center -append \
#        $DIRECTORY/Subtitle.png    -trim +repage -resize ${subtitleWidthValue}x -bordercolor none -border 0x${titleBorderValue}  -gravity south  -append  -gravity center  \
#     -background none \
#        $DIRECTORY/Name.png        -trim +repage -resize x${nameHeightValue}  -gravity center -append \
#        $DIRECTORY/Affiliation.png -trim +repage -resize x${nameHeightValue} -bordercolor none -border 0x${nameBorderValue}  -gravity south  -append \
#        $DIRECTORY/URL.png         -trim +repage -resize x${nameHeightValue}  -gravity south  -append  \
#          -gravity southeast -geometry +${indentValue}+${indentValue}  \
# "$OUTPUT"


# gm composite -size ${WIDTH}x${HEIGHT} xc:none \
#    -gravity Center -geometry ${titleWidthValue}x $DIRECTORY/Title.png  \
#    -gravity SouthEast -geometry x${nameHeightValue} $DIRECTORY/URL.png  \
# "$OUTPUT"


tempDirectory=`mktemp -d`

gm convert $DIRECTORY/Title.png -trim \
   -resize ${titleWidthValue}x \
   ${tempDirectory}/title.miff
gm convert $DIRECTORY/Subtitle.png -trim \
   -resize ${subtitleWidthValue}x \
   -bordercolor none -border 0x${titleBorderValue} \
   ${tempDirectory}/subtitle.miff
gm convert -gravity Center -background none -append \
   ${tempDirectory}/title.miff ${tempDirectory}/subtitle.miff ${tempDirectory}/logo.miff


gm convert $DIRECTORY/Name.png -trim \
   -resize x${nameHeightValue} \
   ${tempDirectory}/name.miff
gm convert $DIRECTORY/Affiliation.png -trim \
   -resize x${nameHeightValue} \
   -bordercolor none -border 0x${nameBorderValue} \
   ${tempDirectory}/affiliation.miff
gm convert $DIRECTORY/URL.png -trim \
   -resize x${nameHeightValue} \
   ${tempDirectory}/url.miff
gm convert -gravity Center -background none -append \
   ${tempDirectory}/name.miff ${tempDirectory}/affiliation.miff ${tempDirectory}/url.miff \
   ${tempDirectory}/contact.miff


gm composite -size ${WIDTH}x${HEIGHT} \
   -gravity Center ${tempDirectory}/logo.miff \
   xc:none ${tempDirectory}/layer-contact.miff
gm composite -size ${WIDTH}x${HEIGHT} \
   -gravity SouthEast -geometry +${indentValue}+${indentValue} contact.miff \
   xc:none ${tempDirectory}/layer-logo.miff


gm composite ${tempDirectory}/layer-contact.miff ${tempDirectory}/layer-logo.miff "$OUTPUT"
