#!/bin/bash -e
#
# MELODIC Logo Script
# Copyright (C) 2017-2018 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -lt 3 ] ; then
   echo >&2 "Usage: $0 output_file caption width"
   exit 1
fi
OUTPUT="$1"
if [ ! -e "$2" ] ; then
   echo >&2 "ERROR: Caption file $2 does not exist!"
   exit 1
fi
CAPTION="`cat "$2"`"
WIDTH="$3"


# convert -size ${WIDTH}x42 xc:transparent \
#    \( -background Gold -fill "#02266b" \
#       -font Helvetica-Bold -pointsize 24 \
#       -gravity center \
#       label:"$CAPTION"  \) -composite \
#    "${OUTPUT}"

gm convert \
   -size ${WIDTH}x42 xc:#FFD70044 \
   -fill "#02266b" \
   -font Helvetica-Bold -pointsize 24 \
   -gravity Center \
   -draw "text 0,1 \"${CAPTION}\"" \
   "${OUTPUT}"
