#!/bin/sh -e

PACKAGES=""
if [ "$1" = "node" ] ; then
   PACKAGES="nornet-api nornet-management nornet-node"
elif [ "$1" = "tunnelbox" ] ; then
   PACKAGES="nornet-api nornet-management nornet-node nornet-trace-service nornet-tunnelbox"
elif [ "$1" = "monitor" ] ; then
   PACKAGES="nornet-api nornet-management nornet-node nornet-monitor nornet-artwork"
elif [ "$1" = "display" ] ; then
   PACKAGES="nornet-api nornet-management nornet-node nornet-display"
elif [ "$1" = "filesrv" ] ; then
   PACKAGES="nornet-api nornet-management nornet-node nornet-filesrv"
elif [ "$1" = "server" ] ; then
   PACKAGES="nornet-api nornet-management nornet-server"
else
   echo >&2 "Usage: $0 [tunnelbox|node|monitor|display|filesrv|server] [development]"
   exit 1
fi
if [ "$2" != "" ] ; then
   PACKAGES="$PACKAGES nornet-development"
fi

sudo rm -f /var/cache/pbuilder/result/*
./build-deb

echo "Purging $PACKAGES ..."
sudo dpkg -P $PACKAGES || true

for package in $PACKAGES ; do
   echo "Installing ${package} ..."
   sudo dpkg -i /var/cache/pbuilder/result/${package}*.deb || true
done
sudo apt-get install -f
