.\" HENCSAT System-Info
.\" Copyright (C) 2013-2019 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd June 6, 2013
.Dt HENCSAT-System-Info 1
.Os HENCSAT-System-Info
.\" ###### Name #############################################################
.Sh NAME
.Nm HENCSAT-System-Info
.Nd HENCSAT HENCSAT-System-Info
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm HENCSAT-System-Info
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm HENCSAT-System-Info
print some basic information on the system, including uptime, software and
network information.
.Pp
.\" .\" ###### Arguments ########################################################
.\" .Sh ARGUMENTS
.\" The following options are available:
.\" .Bl -tag -width indent
.\" .It ...
.\" .El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It HENCSAT-System-Info
.El
