#!/bin/sh -e

# Include the GRUB helper library for grub-mkconfig.
. "/usr/share/grub/grub-mkconfig_lib"

# ====== MELODIC theme =======================================================
echo >&2 "Using MELODIC Compute theme!"

echo "insmod jpeg"   # Load JPEG reader!
echo "if background_image `make_system_path_relative_to_its_root "/boot/MELODIC/MELODICCompute1-1024x768.jpeg"`; then"
echo "   set menu_color_normal=red/black"
echo "   set menu_color_highlight=blue/red"
echo "   set color_normal=red/black"
echo "fi"
